config/routes.rb
Rails.application.routes.draw do
root 'patients#index'
 resources :patients do
  	resources :reports
 end
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :reports, dependent: :destroy, index_errors: true
	accepts_nested_attributes_for :reports
	validates :firstName, presence: true
	validates :lastName, presence: true
	validates :age, presence: true
	validates :sex, presence: true
	validates :address, presence: true
end

app/models/report.rb
class Report < ApplicationRecord
	include ActiveModel::Validations
  include ActiveModel::Conversion
  belongs_to :patient
  validates :symp, presence: true
  validates :analysis, presence: true
  validates :presc, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:firstName, :lastName, :sex, :age, :address)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @patient = Patient.find(params[:patient_id])
    @report = @patient.reports.new(report_params)
    
    respond_to do |format|
      if @report.save
        format.html { redirect_to patient_path(@patient), notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:symp, :analysis, :presc, :patient_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Consul</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Consulting room</a>
    </div>

  </div>
  

	</nav>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    
    <div class="alert alert-danger">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:
      </h2>

      <ul class="rails-bootstrap-forms-error-summary">
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <br>
  <% end %>
  
  <div class="field form-group">
    <%= form.label :firstName, class: 'col-sm-2 control-label' %>
    <div >
    <%= form.text_field :firstName, id: :patient_firstName %>
    </div>
  </div>

  <div class="field form-group">
    <%= form.label :lastName, class: 'col-sm-2 control-label' %>
    <div >
    <%= form.text_field :lastName, id: :patient_lastName %>
    </div>
  </div>

  <div class="field form-group">
    <%= form.label :sex, class: 'col-sm-2 control-label' %>
    <div >
    <%= form.text_field :sex, id: :patient_sex %>
    </div>
  </div>

  <div class="field form-group">
    <%= form.label :age, class: 'col-sm-2 control-label' %>
    <div >
    <%= form.number_field :age, id: :patient_age %>
    </div>
  </div>

  <div class="field form-group">
    <%= form.label :address, class: 'col-sm-2 control-label' %>
    <div >
    <%= form.text_field :address, id: :patient_address %>
    </div>
  </div>
  
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
    <br>
      <%= form.submit %>
      </div>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients</h1>
<table class="table">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.firstName %></td>
        <td><%= patient.lastName %></td>
        <td><%= link_to 'Profile', patient, class: 'btn btn-primary'%></td>
        <!--
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
        -->

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path, class: 'btn btn-default' %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path , class: 'btn btn-default'%>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @patient.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @patient.lastName %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @patient.sex %>
</p>

<p>
  <strong>Age:</strong>
  <%= @patient.age %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>
<h2>Reports</h2>
<table class="table">
  <thead>
    <tr>
      <th>Symp</th>
      <th>Analysis</th>
      <th>Prescription</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @patient.reports.each do | report| %>
  <tr>
        <td><%= report.symp %></td>
        <td><%= report.analysis %></td>
        <td><%= report.presc %></td>
        
      </tr>
<% end %>
</tbody>
</table>
<%= link_to 'New Report', new_patient_report_path(@patient), class: 'btn btn-default' %>
<br>
<%= link_to 'Back', patients_path, class: 'btn btn-default' %>

app/views/reports/_form.html.erb
<%= form_with(model: [ @patient, @report ], url: patient_reports_path) do |form| %>

  <% if report.errors.any? %>
  <h2>jajajjaja xdxdxdxd</h2>
  <div class="alert alert-danger">
    
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul class="rails-bootstrap-forms-error-summary">
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    
    </div>

  <% end %>


  <div class="field form-group">
    <%= form.label :symp, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= form.text_area :symp, id: :report_symp %>
    </div>
  </div>

  <div class="field form-group">
    <%= form.label :analysis, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= form.text_area :analysis, id: :report_analysis %>
    </div>
  </div>

  <div class="field form-group">
    <%= form.label :presc, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= form.text_area :presc, id: :report_presc %>
    </div>
  </div>

 

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Symp</th>
      <th>Analysis</th>
      <th>Presc</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.symp %></td>
        <td><%= report.analysis %></td>
        <td><%= report.presc %></td>
        <td><%= report.patient %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', patient_path(params[:patient_id], @patient_report), class: 'btn btn-default'%>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symp:</strong>
  <%= @report.symp %>
</p>

<p>
  <strong>Analysis:</strong>
  <%= @report.analysis %>
</p>

<p>
  <strong>Presc:</strong>
  <%= @report.presc %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @report.patient %>
</p>